### ISSUE TITLE
Can't input anything inside TextInput

### ISSUE THREAD

**Issue by marzukiberg** [SreeramThatavarthi/weatherapp#2]
Hello, sir @SreeramThatavarthi 
City Input box isn't working or it's not yet?
If you don't mind i would like to fix this in order to complete my first Hacktoberfest, thanks!

**Comment by SreeramThatavarthi** [comment]
Oh sry.I have worked on it and just now fixed it.Just now i have seen your
mail.

**Comment by marzukiberg** [comment]
@SreeramThatavarthi 
Ok, thanks, sir!
Could i suggest something? I thinks it's look better if the Night Mode append to entire body not just in input only...

**Comment by SreeramThatavarthi** [comment]
Yeah good.I didnt append night mode to my app.It was done by one of my
friend in this hacktober fest
.Thank you
